# Array In Python

In [1]:
#import numpy library
import numpy as np

## array

In [2]:
# store list in a reference variable
x = [2,3,4,5,6]

In [4]:
# the list convert in array via reference variable
np.array(x)

array([2, 3, 4, 5, 6])

In [5]:
# the list convert in array
array_x = np.array([4,5,6])

In [6]:
# print the array variable
print(array_x)

[4 5 6]


In [7]:
# check the type of variable
type(array_x)

numpy.ndarray

### ndim and shape

In [8]:
# check variable number of dimensional attribute 
array_x.ndim

1

In [9]:
# check the shape of array
array_x.shape

(3,)

In [10]:
# use 2d array
array_2d = np.array([[2,4,6,8],[1,3,5,7]])

In [12]:
# print the 2d array
print(array_2d)

[[2 4 6 8]
 [1 3 5 7]]


In [13]:
# check ndim of 2d array
array_2d.ndim

2

In [14]:
# check the shape of 2d array
array_2d.shape

(2, 4)

### create the array as zeros, ones, empty

In [16]:
# create one dimensional zeros array
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
# create 2d zeros array
np.zeros((4,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [18]:
# create 1d array with value of 1
np.ones(13)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
# create 2d array with value of 1
np.ones((2,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [21]:
# create multi dimensional empty array with garbage value
arr_empty = np.empty((3,3,4))

In [22]:
# check the dimensional of array
arr_empty.ndim

3

In [23]:
# check the shape of array
arr_empty.shape

(3, 3, 4)

In [25]:
# print the array
print(arr_empty)
# value is a garbage value

[[[3.19411549e+132 2.00412556e-312 7.76342176e-307 1.33360338e+241]
  [5.51082307e-310 2.00497879e+190 2.23754509e-312 1.22135695e-306]
  [1.33360343e+241 5.99973090e-310 4.47125211e+233 2.40730476e-312]]

 [[2.17570503e-306 1.33360349e+241 6.70593110e-310 5.03961303e-266]
  [1.13266807e+277 6.42301085e-295 4.97659562e+043 5.40840706e-308]
  [1.33360306e+241 2.95806213e-311 3.38758803e-307 9.11571148e-304]]

 [[5.70271043e-270 3.07992142e-289 1.00513216e-197 1.04687672e-144]
  [1.09233703e-197 6.86286111e-140 8.00617372e-169 9.66010074e-145]
  [1.18499229e-303 4.28354915e-321 7.06200199e-311 1.73444507e-304]]]


### np.arange()

In [26]:
# create the array with arange function with start and end point
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
# create the array with arange function with start and end point with steps
np.arange(2,40,5)

array([ 2,  7, 12, 17, 22, 27, 32, 37])

### Data Types for arrays

In [28]:
array_int = np.array([2,3,4,5], dtype = np.int32)
array_float = np.array([2,3,4,5], dtype = np.float64)

In [29]:
array_int

array([2, 3, 4, 5])

In [30]:
array_float

array([2., 3., 4., 5.])

In [31]:
array_float.dtype

dtype('float64')

### astype

In [32]:
array1 = np.array([2,4,6,8,10])

In [33]:
array1

array([ 2,  4,  6,  8, 10])

In [34]:
array1.dtype

dtype('int32')

In [35]:
array1_float = array1.astype(np.float64)

In [36]:
array1_float

array([ 2.,  4.,  6.,  8., 10.])

In [37]:
array1_float.dtype

dtype('float64')

In [38]:
array_float = np.array([2.33, 3.4, 5.9, 4.23])

In [39]:
array_float

array([2.33, 3.4 , 5.9 , 4.23])

In [40]:
array_float.dtype

dtype('float64')

In [41]:
array_int = array_float.astype(np.int32)

In [42]:
array_int

array([2, 3, 5, 4])

### Operations on Arrays

In [43]:
array1 = np.array([[2,4,6],[1,3,5]])

In [44]:
array2 = np.array([[12,14,16],[13,15,17]])

In [45]:
array1 + array1

array([[ 4,  8, 12],
       [ 2,  6, 10]])

In [46]:
array1

array([[2, 4, 6],
       [1, 3, 5]])

In [47]:
array1 + array2

array([[14, 18, 22],
       [14, 18, 22]])

In [48]:
array2

array([[12, 14, 16],
       [13, 15, 17]])

In [49]:
array1 - array2

array([[-10, -10, -10],
       [-12, -12, -12]])

In [50]:
array2 - array2

array([[0, 0, 0],
       [0, 0, 0]])

In [51]:
array1 * array2

array([[24, 56, 96],
       [13, 45, 85]])

In [52]:
array1/array2

array([[0.16666667, 0.28571429, 0.375     ],
       [0.07692308, 0.2       , 0.29411765]])

In [53]:
array1**0.5

array([[1.41421356, 2.        , 2.44948974],
       [1.        , 1.73205081, 2.23606798]])

### Indexing and Slicing Arrays

In [54]:
array1 = np.arange(15)

In [55]:
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [56]:
array1[7]

7

In [57]:
array1[-2]

13

In [58]:
array1 = np.arange(2,25,3)

In [59]:
array1

array([ 2,  5,  8, 11, 14, 17, 20, 23])

In [60]:
array1[4]

14

In [61]:
array1[2:5]

array([ 8, 11, 14])

In [62]:
array1[-2]

20

In [63]:
x = array1[2:5]

In [64]:
x

array([ 8, 11, 14])

In [65]:
x = 16

In [66]:
array1

array([ 2,  5,  8, 11, 14, 17, 20, 23])

### Indexing and Slicing Arrays

In [67]:
array1 = np.arange(14)

In [68]:
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [69]:
array1[3]

3

In [70]:
array1 = np.arange(2,35,3)

In [71]:
array1

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32])

In [72]:
array1[4]

14

In [73]:
array1[-3]

26

In [74]:
array1[3:7]

array([11, 14, 17, 20])

In [75]:
array1[3:7] = 16

In [76]:
array1

array([ 2,  5,  8, 16, 16, 16, 16, 23, 26, 29, 32])

In [77]:
array_slice = array1[3:7]

In [78]:
array_slice

array([16, 16, 16, 16])

In [79]:
array_slice[3] = 28

In [80]:
array1

array([ 2,  5,  8, 16, 16, 16, 28, 23, 26, 29, 32])

In [81]:
array_slice[1:3] = 123

In [82]:
array1

array([  2,   5,   8,  16, 123, 123,  28,  23,  26,  29,  32])

### Indexing and Slicing 2d Arrays

In [83]:
array2 = np.array([[2,4,6],[1,3,5],[22,23,34],[13,15,19]])

In [84]:
array2

array([[ 2,  4,  6],
       [ 1,  3,  5],
       [22, 23, 34],
       [13, 15, 19]])

In [85]:
array2.ndim

2

In [86]:
array2[0]

array([2, 4, 6])

In [87]:
array2[2]

array([22, 23, 34])

In [88]:
array2[-2]

array([22, 23, 34])

In [89]:
array2[0][1]

4

In [90]:
array2[3][0]

13

In [91]:
x = array2[3]

In [92]:
x

array([13, 15, 19])

In [93]:
x[0]

13

In [94]:
array2[2][1]

23

In [95]:
array2[2,1]

23

In [96]:
array2[1:3]

array([[ 1,  3,  5],
       [22, 23, 34]])

In [97]:
array2[2:3]

array([[22, 23, 34]])

In [98]:
array2[:3]

array([[ 2,  4,  6],
       [ 1,  3,  5],
       [22, 23, 34]])

In [99]:
array2

array([[ 2,  4,  6],
       [ 1,  3,  5],
       [22, 23, 34],
       [13, 15, 19]])

In [100]:
array2[:, 1:]

array([[ 4,  6],
       [ 3,  5],
       [23, 34],
       [15, 19]])

In [101]:
array2[:2, 1:]

array([[4, 6],
       [3, 5]])

In [102]:
array2[:2, :2]

array([[2, 4],
       [1, 3]])

In [103]:
array2[:, 1]

array([ 4,  3, 23, 15])

In [104]:
array2[:, 1:2]

array([[ 4],
       [ 3],
       [23],
       [15]])

In [105]:
array2[:2, :2] = 122

In [106]:
array2

array([[122, 122,   6],
       [122, 122,   5],
       [ 22,  23,  34],
       [ 13,  15,  19]])

### Boolean Indexing

In [107]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [108]:
states = np.array(['NY', 'DC','CA','NY','CA','DC','NY','CA'])

In [109]:
num = np.random.randn(8,4)

In [110]:
states

array(['NY', 'DC', 'CA', 'NY', 'CA', 'DC', 'NY', 'CA'], dtype='<U2')

In [111]:
num

array([[ 0.14197663, -1.91128969,  0.30917649, -0.58152874],
       [ 0.16938817, -2.59543849,  0.07877336,  0.58018358],
       [-1.02965121,  1.08225114,  0.44547976, -0.10938513],
       [-0.56089767, -0.53605282, -0.66619034, -0.68721485],
       [-0.65841573,  0.07924659, -0.37857312, -2.16348771],
       [ 1.6898111 ,  0.06361877, -0.66306213,  0.52066595],
       [ 0.34731487,  0.24096135, -0.84006151, -0.93574439],
       [-1.27722494, -0.83834191,  0.68510113,  0.67188275]])

In [112]:
num.shape

(8, 4)

In [113]:
states == 'NY'

array([ True, False, False,  True, False, False,  True, False])

In [114]:
num[states == 'NY']

array([[ 0.14197663, -1.91128969,  0.30917649, -0.58152874],
       [-0.56089767, -0.53605282, -0.66619034, -0.68721485],
       [ 0.34731487,  0.24096135, -0.84006151, -0.93574439]])

In [115]:
num[states == 'NY', 1:]

array([[-1.91128969,  0.30917649, -0.58152874],
       [-0.53605282, -0.66619034, -0.68721485],
       [ 0.24096135, -0.84006151, -0.93574439]])

In [116]:
num[states == 'NY',1:3 ]

array([[-1.91128969,  0.30917649],
       [-0.53605282, -0.66619034],
       [ 0.24096135, -0.84006151]])

In [117]:
num[states == 'NY', 0]

array([ 0.14197663, -0.56089767,  0.34731487])

In [118]:
num[states == 'NY', 0:1]

array([[ 0.14197663],
       [-0.56089767],
       [ 0.34731487]])

### == , ! = 

In [119]:
states != 'NY'

array([False,  True,  True, False,  True,  True, False,  True])

In [120]:
states != 'DC'

array([ True, False,  True,  True,  True, False,  True,  True])

In [121]:
num[~(states == 'NY')]

array([[ 0.16938817, -2.59543849,  0.07877336,  0.58018358],
       [-1.02965121,  1.08225114,  0.44547976, -0.10938513],
       [-0.65841573,  0.07924659, -0.37857312, -2.16348771],
       [ 1.6898111 ,  0.06361877, -0.66306213,  0.52066595],
       [-1.27722494, -0.83834191,  0.68510113,  0.67188275]])

### == ~ |

In [122]:
nydc = (states == 'NY') | (states == 'DC')

In [123]:
num[nydc]

array([[ 0.14197663, -1.91128969,  0.30917649, -0.58152874],
       [ 0.16938817, -2.59543849,  0.07877336,  0.58018358],
       [-0.56089767, -0.53605282, -0.66619034, -0.68721485],
       [ 1.6898111 ,  0.06361877, -0.66306213,  0.52066595],
       [ 0.34731487,  0.24096135, -0.84006151, -0.93574439]])

### Fancy Indexing !

- means indexing using int arrays

In [124]:
array1 = np.empty((12,5))

In [125]:
for x in range(12):
    array1[x] = x

In [126]:
array1

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.],
       [10., 10., 10., 10., 10.],
       [11., 11., 11., 11., 11.]])

In [127]:
array1[[2,4,6,8]]

array([[2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8.]])

In [128]:
array1[[2,3,10,11]]

array([[ 2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.],
       [10., 10., 10., 10., 10.],
       [11., 11., 11., 11., 11.]])

In [129]:
array1[[-1]]

array([[11., 11., 11., 11., 11.]])

In [130]:
array1[[-2,-4]]

array([[10., 10., 10., 10., 10.],
       [ 8.,  8.,  8.,  8.,  8.]])

In [131]:
array2 = np.arange(40).reshape((8,5))

In [132]:
array2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [133]:
array2[[1,2],[0,1]]

array([ 5, 11])

### 27, 33, 39   27 = (5,2)  33 = (6,3) 39 = (7,4)

In [153]:
array2[[5,6,7],[2,3,4]]

array([27, 33, 39])